### ISSUE TITLE
After installing from cocoapods getting alot of error

### ISSUE THREAD

**Issue by ytpm** [nikitabelosludtcev/ActivationToggle#1]
Mainly error types such as:

`'kCAMediaTimingFunctionEaseInEaseOut' has been renamed to 'CAMediaTimingFunctionName.easeInEaseOut'`
`'kCAFillModeForwards' has been renamed to 'CAMediaTimingFillMode.forwards'`

Please check it.
Thanks.

**Comment by nikitabelosludtcev** [comment]
Fixed in 0.0.2

**Comment by nikitabelosludtcev** [comment]
Fixed in 0.0.2
